name: Ship to Prod (all-in-one)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ship-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: skylink360-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: skylink360-app

      - name: Build project
        run: npm run build
        working-directory: skylink360-app

      # --- Optional Vercel deploy (comment out if not using) ---
      # requires repo secrets: VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
      - name: Deploy to Vercel (optional)
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        run: npx vercel --prod --yes --token="${{ secrets.VERCEL_TOKEN }}" --scope="${{ secrets.VERCEL_ORG_ID }}"
        working-directory: skylink360-app

      # --- Always try to trigger MasterLiveViewing sync, but NEVER fail build if it errors ---
      - name: Trigger MasterLiveViewing sync
        uses: benc-uk/workflow-dispatch@v1
        continue-on-error: true          # <-- fail-safe
        with:
          # The workflow file name in MasterLiveViewing (adjust if different)
          workflow: sync-skylink360.yml
          # Target repo to trigger
          repo: antoniolatham-hue/MasterLiveViewing
          ref: main
          token: ${{ secrets.WORKFLOW_PAT }}   # see notes below

      # Optional: show a friendly log if the dispatch failed but build succeeded
      - name: Note if sync trigger failed
        if: ${{ failure() }}
        run: echo "MasterLiveViewing sync trigger failed, but build/deploy completed."
