name: Global Push & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes

permissions:
  contents: write            # allow committing/pushing changes

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHToken }}   # <-- must match your secret name

      - name: Configure git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Find liveMonitor.json
        id: find_json
        run: |
          FILE="$(git ls-files | grep -Ei '(^|/)liveMonitor\.json$' || true)"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"

      - name: Copy or create liveMonitor.json -> masterlive/data
        run: |
          mkdir -p masterlive/data
          if [ -n "${{ steps.find_json.outputs.file }}" ]; then
            echo "Found: ${{ steps.find_json.outputs.file }}"
            cp "${{ steps.find_json.outputs.file }}" masterlive/data/liveMonitor.json
          else
            echo "liveMonitor.json not found. Creating a blank one."
            echo '{}' > masterlive/data/liveMonitor.json
          fi

      - name: Commit & push if there are changes
        run: |
          if ! git diff --quiet; then
            git add -A
            git commit -m "Auto: sync liveMonitor.json and deploy [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Deploy (add your commands here)
        run: |
          # Example placeholder — replace with your real deploy steps
          echo "🚀 Deploy step placeholder (add your deploy commands)"
