name: Ship to Prod (all-in-one)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ship-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: skylink360-app/package-lock.json

      - name: Install dependencies
        working-directory: skylink360-app
        run: npm ci

      - name: Build app
        working-directory: skylink360-app
        run: npm run build

      - name: Deploy app
        working-directory: skylink360-app
        run: npm run deploy

      - name: Trigger MasterLiveViewing sync
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sync-skylink360.yml
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
